name: Update Current Step
on:
  schedule:
    - cron: '0 0 * * *'  # KST 09:00 (UTC 00:00)
    - cron: '0 5 * * *'  # KST 14:00 (UTC 05:00)
    - cron: '0 8 * * *'  # KST 17:00 (UTC 08:00)
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios

      - name: Debug Secrets
        run: |
          echo "Available secrets: ${{ toJSON(secrets) }}"
          echo "FIRESTORE_PROJECT_ID direct: ${{ secrets.FIRESTORE_PROJECT_ID }}"
          echo "GOOGLE_API_KEY direct: ****"

      - name: Update Firestore currentStep
        env:
          FIRESTORE_PROJECT_ID: ${{ secrets.FIRESTORE_PROJECT_ID }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          echo "Env - FIRESTORE_PROJECT_ID: $FIRESTORE_PROJECT_ID"
          echo "Env - GOOGLE_API_KEY: ****"
          if [ -z "$FIRESTORE_PROJECT_ID" ] || [ -z "$GOOGLE_API_KEY" ]; then
            echo "Error: One or more environment variables are missing"
            exit 1
          fi
          node scripts/update-step.js